name = "group-guard-consumer"
main = "index.js"
compatibility_date = "2024-04-05"
logpush = true

[[d1_databases]]
binding = "DB"
database_name = "group_guard"
database_id = "db805d1a-62ee-45d4-975f-4fca9817ab77"

[[queues.consumers]]
queue = "group-guard-queue"
